'use client'

import { useState } from 'react'
import { PageHeader } from '@/components/ui/PageHeader'
import { ComponentPreview } from '@/components/ui/ComponentPreview'
import { CodeBlock } from '@/components/ui/CodeBlock'
import { PropsTable } from '@/components/ui/PropsTable'
import { AccessibilityChecklist, Anatomy, BehaviorGrid, ComponentDocSection, ComponentDocumentation, ContentGuidelines, GuidanceList, KeyboardTable, RelatedComponents, StateMatrix } from '@/components/docs/ComponentDocumentation'

const PROPS = [
  { name: 'value', type: 'string', default: 'undefined', description: 'Controlled query.' }, { name: 'defaultValue', type: 'string', default: "''", description: 'Initial uncontrolled query.' }, { name: 'onValueChange', type: '(value: string) => void', default: 'undefined', description: 'Runs whenever the query changes.' }, { name: 'onSearch', type: '(value: string) => void', default: 'undefined', description: 'Runs when Enter or submit activates search.' }, { name: 'onClear', type: '() => void', default: 'undefined', description: 'Runs after the clear control empties the query.' }, { name: 'label', type: 'ReactNode', default: 'undefined', description: 'Visible field label.' }, { name: 'helperText', type: 'ReactNode', default: 'undefined', description: 'Supporting instruction below the field.' }, { name: 'resultText', type: 'ReactNode', default: 'undefined', description: 'Live result summary.' }, { name: 'loading', type: 'boolean', default: 'false', description: 'Shows query resolution progress.' }, { name: 'clearable', type: 'boolean', default: 'true', description: 'Shows clear when the query has content.' }, { name: 'showSubmitButton', type: 'boolean', default: 'false', description: 'Shows an explicit search button.' }, { name: 'variant', type: "'outlined' | 'filled' | 'underlined'", default: "'outlined'", description: 'Controls field treatment.' }, { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Controls height, spacing, and type.' },
] as const
const BASIC = `import { SearchField } from 'omverse-ui'

<SearchField
  label="Search projects"
  value={query}
  onValueChange={setQuery}
  onSearch={runSearch}
  resultText="24 results"
  showSubmitButton
/>`
const REMOTE = `<SearchField
  aria-label="Search audit events"
  value={query}
  onValueChange={setQuery}
  onSearch={() => refetch()}
  loading={queryState.isFetching}
  resultText={queryState.data ? \`${'${queryState.data.total}'} events\` : undefined}
/>`

function SearchPreview() { const [query, setQuery] = useState('migration'); const [submitted, setSubmitted] = useState('migration'); const total = submitted ? 24 : 148; return <div className="search-field-demo"><label htmlFor="project-search-demo">Search projects</label><div role="search"><span aria-hidden>⌕</span><input id="project-search-demo" type="search" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') setSubmitted(query) }} />{query && <button type="button" aria-label="Clear search" onClick={() => { setQuery(''); setSubmitted('') }}>×</button>}<button type="button" aria-label="Search" onClick={() => setSubmitted(query)}>→</button></div><footer><small>Search by name, owner, or project ID.</small><output aria-live="polite">{total} results</output></footer></div> }

export default function SearchFieldPage() { return <div><PageHeader breadcrumb={['Components', 'Enterprise', 'SearchField']} title="SearchField" description="SearchField captures and submits a query without owning suggestions or results." tags={['Controlled query', '3 variants', '3 sizes', 'Loading', 'Result summary']} /><ComponentDocumentation>
  <ComponentDocSection id="overview" title="Overview" description="Use SearchField to find content in a page, collection, or remote data set when the application owns result retrieval and presentation."><div className="component-doc-stack"><ComponentPreview title="Project search" description="Edit the query, press Enter, clear it, or use the explicit submit control."><SearchPreview /></ComponentPreview><CodeBlock filename="ProjectSearch.tsx" code={BASIC} /></div></ComponentDocSection>
  <ComponentDocSection id="anatomy" title="Anatomy" description="SearchField combines a search affordance, editable query, clear and optional submit controls, plus guidance or live result context."><Anatomy preview={<div className="component-anatomy-visual search-field-anatomy"><label>Search projects</label><section><i>⌕</i><span>migration</span><b>×</b><em>→</em></section><footer><small>Search by name or ID.</small><strong>24 results</strong></footer><span className="component-anatomy-marker component-anatomy-marker--leader-down" style={{ top: -34, left: 32 }}>1</span><span className="component-anatomy-marker component-anatomy-marker--leader-up" style={{ bottom: -34, left: 88 }}>2</span><span className="component-anatomy-marker component-anatomy-marker--leader-down" style={{ top: -34, right: 70 }}>3</span><span className="component-anatomy-marker component-anatomy-marker--leader-down" style={{ top: -34, right: 24 }}>4</span><span className="component-anatomy-marker component-anatomy-marker--leader-up" style={{ bottom: -34, right: 24 }}>5</span></div>} items={[{ number: 1, name: 'Search icon', description: 'Identifies the field purpose without replacing its label.' }, { number: 2, name: 'Query input', description: 'Captures free-form search terms.' }, { number: 3, name: 'Clear control', description: 'Empties a non-empty query and retains focus.' }, { number: 4, name: 'Submit control', description: 'Explicitly runs search when needed.' }, { number: 5, name: 'Search context', description: 'Shows guidance and a live result summary.' }]} /></ComponentDocSection>
  <ComponentDocSection id="when-to-use" title="When to use" description="Use SearchField when people know terms that identify content and results are presented elsewhere."><GuidanceList tone="do" items={[{ title: 'Search a collection', description: 'Find projects, people, events, or records using recognizable terms.' }, { title: 'Submit remote queries', description: 'Use explicit submission when requests are expensive or intentional.' }, { title: 'Summarize results', description: 'Keep a concise result count connected to the current query.' }]} /></ComponentDocSection>
  <ComponentDocSection id="when-not-to-use" title="When not to use" description="Use a selection or command pattern when the field must own suggestions or trigger application actions."><GuidanceList tone="dont" items={[{ title: 'Do not select values', description: 'Use Combobox when a result becomes a form value.' }, { title: 'Do not execute commands', description: 'Use CommandBar for searchable actions and navigation.' }, { title: 'Do not replace filters', description: 'Use FilterBar for structured facets and governed conditions.' }]} /></ComponentDocSection>
  <ComponentDocSection id="variants" title="Variants" description="Three treatments and sizes let SearchField fit standalone pages, grouped forms, and compact productivity surfaces."><BehaviorGrid items={[{ icon: 'ti-border-all', title: 'Outlined', description: 'Default boundary for independent search.' }, { icon: 'ti-square-filled', title: 'Filled', description: 'Tonal field within grouped surfaces.' }, { icon: 'ti-minus', title: 'Underlined', description: 'Restrained treatment for embedded search.' }, { icon: 'ti-arrows-maximize', title: 'Sizes', description: 'Small, medium, and large maintain predictable controls.' }]} /></ComponentDocSection>
  <ComponentDocSection id="states" title="States" description="SearchField coordinates query entry and resolution feedback while applications own the result lifecycle."><StateMatrix rows={[{ state: 'Empty', trigger: 'No query', visual: 'Search icon and placeholder', interaction: 'Ready for input' }, { state: 'Populated', trigger: 'Query entered', visual: 'Query and clear control', interaction: 'Edit, clear, or submit' }, { state: 'Focused', trigger: 'Input receives focus', visual: 'Primary border and ring', interaction: 'Text entry active' }, { state: 'Loading', trigger: 'Search resolving', visual: 'Progress icon', interaction: 'Query remains visible' }, { state: 'Results', trigger: 'Response available', visual: 'Live result summary', interaction: 'Results remain application-owned' }, { state: 'Disabled', trigger: 'Search unavailable', visual: 'Reduced emphasis', interaction: 'Not operable' }]} /></ComponentDocSection>
  <ComponentDocSection id="behavior" title="Behavior" description="SearchField owns query mechanics while debouncing, network requests, routing, result ranking, and analytics remain application concerns."><BehaviorGrid items={[{ icon: 'ti-keyboard', title: 'Submit', description: 'Enter and the optional submit control call onSearch.' }, { icon: 'ti-x', title: 'Clear', description: 'Escape or clear empties a populated query and restores input focus.' }, { icon: 'ti-loader', title: 'Progress', description: 'Loading replaces clear with a non-blocking progress indicator.' }, { icon: 'ti-speakerphone', title: 'Result summary', description: 'Result text uses a polite live status.' }]} /></ComponentDocSection>
  <ComponentDocSection id="accessibility" title="Accessibility" description="SearchField retains native search input behavior with persistent labeling and connected search feedback."><div className="component-doc-stack"><KeyboardTable rows={[{ keys: ['Enter'], action: 'Submits the current query.' }, { keys: ['Esc'], action: 'Clears a populated query when clearable.' }, { keys: ['Tab'], action: 'Moves through input and visible action controls.' }]} /><AccessibilityChecklist items={['Provide a visible label or an explicit aria-label.', 'Name clear and submit controls independently from their icons.', 'Announce result counts politely without moving focus.', 'Do not announce loading continuously during every keystroke.', 'Keep result content after the field in a logical reading order.', 'Use Combobox semantics instead when suggestions are selectable.']} /></div></ComponentDocSection>
  <ComponentDocSection id="content-guidelines" title="Content guidelines" description="Labels, placeholders, and result summaries should communicate scope without prescribing overly specific queries."><ContentGuidelines rules={[{ label: 'Name the scope', guidance: 'Identify what can be searched.', example: 'Search projects' }, { label: 'Offer useful terms', guidance: 'Describe supported identifiers in helper text.', example: 'Search by name, owner, or project ID.' }, { label: 'Keep placeholders short', guidance: 'Use a natural prompt when the label is already visible.', example: 'Name or project ID' }, { label: 'Quantify results', guidance: 'Use concise localized summaries.', example: '24 results' }]} /></ComponentDocSection>
  <ComponentDocSection id="examples" title="Examples" description="Controlled state supports remote search while loading and result feedback remain aligned with the query."><div className="component-doc-stack"><ComponentPreview title="Remote audit search"><div className="search-field-demo"><div role="search"><span aria-hidden>⌕</span><input type="search" aria-label="Search audit events" defaultValue="access" /><span className="search-field-spinner" aria-label="Searching">↻</span></div><footer><small>Search actor, action, or resource.</small><output>Searching…</output></footer></div></ComponentPreview><CodeBlock filename="AuditSearch.tsx" code={REMOTE} /></div></ComponentDocSection>
  <ComponentDocSection id="props-api" title="Props / API" description="SearchField extends native input attributes except values, change, type, and size replaced by its controlled API."><PropsTable props={PROPS} /></ComponentDocSection>
  <ComponentDocSection id="related-components" title="Related components" description="Choose based on whether people search content, select values, execute commands, or apply structured conditions."><RelatedComponents items={[{ name: 'Combobox', href: '/components/combobox', description: 'Search and select a value', icon: 'ti-list-search' }, { name: 'CommandBar', href: '/components/command-bar', description: 'Search actions and destinations', icon: 'ti-command' }, { name: 'FilterBar', href: '/components/filter-bar', description: 'Apply structured conditions', icon: 'ti-filter' }, { name: 'Input', href: '/components/input', description: 'Capture non-search text values', icon: 'ti-cursor-text' }]} /></ComponentDocSection>
 </ComponentDocumentation></div> }
