'use client'
import { useState } from 'react'
import { PageHeader } from '@/components/ui/PageHeader'
import { ComponentPreview } from '@/components/ui/ComponentPreview'
import { CodeBlock } from '@/components/ui/CodeBlock'
import { PropsTable } from '@/components/ui/PropsTable'
import { AccessibilityChecklist, Anatomy, BehaviorGrid, ComponentDocSection, ComponentDocumentation, ContentGuidelines, GuidanceList, KeyboardTable, RelatedComponents, StateMatrix } from '@/components/docs/ComponentDocumentation'
const PROPS = [{ name: 'children', type: 'ReactNode', default: 'required', description: 'Primary action label.' }, { name: 'onClick', type: '() => void', default: 'undefined', description: 'Runs the primary action.' }, { name: 'items', type: 'readonly SplitButtonItem[]', default: 'required', description: 'Closely related alternatives.' }, { name: 'open', type: 'boolean', default: 'undefined', description: 'Controlled menu visibility.' }, { name: 'defaultOpen', type: 'boolean', default: 'false', description: 'Initial uncontrolled visibility.' }, { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined', description: 'Runs when menu visibility changes.' }, { name: 'onItemSelect', type: '(item) => void', default: 'undefined', description: 'Runs after an enabled alternative is selected.' }, { name: 'menuLabel', type: 'string', default: "'More actions'", description: 'Accessible label for the menu trigger.' }, { name: 'leadingIcon', type: 'IconName', default: 'undefined', description: 'Optional primary action icon.' }, { name: 'disabled', type: 'boolean', default: 'false', description: 'Disables both controls.' }, { name: 'loading', type: 'boolean', default: 'false', description: 'Shows primary action progress and disables both controls.' }, { name: 'loadingText', type: 'ReactNode', default: "'Working…'", description: 'Primary label shown while loading.' }, { name: 'variant', type: "'filled' | 'outlined' | 'tonal'", default: "'filled'", description: 'Controls action emphasis.' }, { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Controls target height and spacing.' }] as const
const BASIC = `import { SplitButton } from 'omverse-ui'

<SplitButton
  leadingIcon="upload"
  onClick={publishNow}
  items={[
    { id: 'draft', label: 'Save as draft', icon: 'bookmark', onSelect: saveDraft },
    { id: 'schedule', label: 'Schedule publish', icon: 'play', onSelect: schedule },
  ]}
>
  Publish
</SplitButton>`
const CONTROLLED = `<SplitButton items={actions} open={open} onOpenChange={setOpen} loading={isPublishing}>Publish</SplitButton>`
function SplitPreview() { const [open, setOpen] = useState(true); const [status, setStatus] = useState('Ready to publish'); return <div className="split-demo"><div><button type="button" onClick={() => setStatus('Published now')}>⇧ Publish</button><button type="button" aria-label="More publish actions" aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen(!open)}>⌄</button>{open && <div role="menu" aria-label="More publish actions"><button role="menuitem" onClick={() => { setStatus('Saved as draft'); setOpen(false) }}>☆ Save as draft</button><button role="menuitem" onClick={() => { setStatus('Publish scheduled'); setOpen(false) }}>▷ Schedule publish</button><button role="menuitem">▤ Save as template</button></div>}</div><p role="status">{status}</p></div> }
export default function SplitButtonPage() { return <div><PageHeader breadcrumb={['Components', 'Enterprise', 'SplitButton']} title="SplitButton" description="SplitButton pairs one primary action with a menu of closely related alternatives." tags={['Primary + menu', '3 variants', '3 sizes', 'Keyboard menu', 'Controlled open']} /><ComponentDocumentation>
<ComponentDocSection id="overview" title="Overview" description="Use SplitButton when one action is clearly the default and a small menu exposes variations of that same intent."><div className="component-doc-stack"><ComponentPreview title="Publish actions" description="Run the default publish action or choose a closely related alternative."><SplitPreview /></ComponentPreview><CodeBlock filename="PublishButton.tsx" code={BASIC} /></div></ComponentDocSection>
<ComponentDocSection id="anatomy" title="Anatomy" description="The control joins a default action and menu trigger while the open menu lists closely related alternatives."><Anatomy preview={<div className="component-anatomy-visual split-anatomy"><header><button>⇧ Publish</button><button>⌄</button></header><section><p>☆ Save as draft</p><p>▷ Schedule publish</p><p>▤ Save as template</p></section><span className="component-anatomy-marker component-anatomy-marker--leader-down" style={{ top: -34, left: 65 }}>1</span><span className="component-anatomy-marker component-anatomy-marker--leader-right" style={{ top: 26, left: -34 }}>2</span><span className="component-anatomy-marker component-anatomy-marker--leader-down" style={{ top: -34, right: 18 }}>3</span><span className="component-anatomy-marker component-anatomy-marker--leader-left" style={{ top: 84, right: -34 }}>4</span><span className="component-anatomy-marker component-anatomy-marker--leader-up" style={{ bottom: -34, left: 95 }}>5</span></div>} items={[{ number: 1, name: 'Primary action', description: 'Runs the most likely action immediately.' }, { number: 2, name: 'Shared boundary', description: 'Communicates that both controls belong to one action family.' }, { number: 3, name: 'Menu trigger', description: 'Opens the related alternatives without running the default.' }, { number: 4, name: 'Action menu', description: 'Provides a named menu surface.' }, { number: 5, name: 'Alternative item', description: 'Runs one closely related action and closes the menu.' }]} /></ComponentDocSection>
<ComponentDocSection id="when-to-use" title="When to use" description="Use when a stable default action accounts for most use while two to five related variations remain useful."><GuidanceList tone="do" items={[{ title: 'Preserve a strong default', description: 'Keep publish, save, create, or export immediately available.' }, { title: 'Group variations', description: 'Offer schedule publish, save draft, or export formats.' }, { title: 'Support repeat work', description: 'Reduce steps for the action people choose most often.' }]} /></ComponentDocSection>
<ComponentDocSection id="when-not-to-use" title="When not to use" description="Use separate controls when actions differ in intent, importance, or consequence."><GuidanceList tone="dont" items={[{ title: 'Do not mix unrelated actions', description: 'Use Toolbar or DropdownMenu for broader command sets.' }, { title: 'Do not hide destructive action', description: 'Separate irreversible actions from a routine default.' }, { title: 'Do not use without a clear default', description: 'Use DropdownMenu when every action has equal likelihood.' }]} /></ComponentDocSection>
<ComponentDocSection id="variants" title="Variants" description="Emphasis and size follow the importance of the shared action family."><BehaviorGrid items={[{ icon: 'ti-square-filled', title: 'Filled', description: 'High-emphasis primary action.' }, { icon: 'ti-border-all', title: 'Outlined', description: 'Medium emphasis on neutral surfaces.' }, { icon: 'ti-palette', title: 'Tonal', description: 'Lower emphasis within grouped workflows.' }, { icon: 'ti-arrows-maximize', title: 'Sizes', description: 'Small, medium, and large preserve matched controls.' }]} /></ComponentDocSection>
<ComponentDocSection id="states" title="States" description="Primary and menu controls share availability and progress while the menu tracks its own visibility and focus."><StateMatrix rows={[{ state: 'Closed', trigger: 'Alternatives hidden', visual: 'Joined primary and trigger', interaction: 'Either control available' }, { state: 'Open', trigger: 'Menu trigger activates', visual: 'Menu below group', interaction: 'First enabled item focused' }, { state: 'Focused item', trigger: 'Keyboard navigation', visual: 'Tonal item surface', interaction: 'Enter selects' }, { state: 'Loading', trigger: 'Primary work active', visual: 'Progress and loading text', interaction: 'Both controls disabled' }, { state: 'Disabled', trigger: 'Action family unavailable', visual: 'Reduced emphasis', interaction: 'No activation' }]} /></ComponentDocSection>
<ComponentDocSection id="behavior" title="Behavior" description="SplitButton owns menu interaction while applications own action execution, confirmation, authorization, and side effects."><BehaviorGrid items={[{ icon: 'ti-player-play', title: 'Primary execution', description: 'Primary action never opens the alternatives menu.' }, { icon: 'ti-menu-2', title: 'Menu selection', description: 'An enabled alternative executes and closes the menu.' }, { icon: 'ti-click', title: 'Dismissal', description: 'Escape and outside pointer interaction close the menu.' }, { icon: 'ti-focus-2', title: 'Focus return', description: 'Selection or Escape returns focus to the trigger.' }]} /></ComponentDocSection>
<ComponentDocSection id="accessibility" title="Accessibility" description="SplitButton exposes two native buttons and a named menu with standard roving keyboard navigation."><div className="component-doc-stack"><KeyboardTable rows={[{ keys: ['Tab'], action: 'Moves between primary action and menu trigger.' }, { keys: ['Enter','Space'], action: 'Runs the focused control or menu item.' }, { keys: ['↓'], action: 'Opens the menu from its trigger or moves to the next item.' }, { keys: ['↑'], action: 'Moves to the previous menu item.' }, { keys: ['Home','End'], action: 'Moves to the first or last item.' }, { keys: ['Esc'], action: 'Closes the menu and returns focus.' }]} /><AccessibilityChecklist items={['Give the trigger a label describing the action family.', 'Keep the primary visible label explicit.', 'Use menu semantics only for executable alternatives.', 'Disable both controls while the primary action is loading.', 'Return focus after selection and dismissal.', 'Keep destructive alternatives separated or clearly labeled.']} /></div></ComponentDocSection>
<ComponentDocSection id="content-guidelines" title="Content guidelines" description="The primary label and alternatives should share one clear verb or outcome family."><ContentGuidelines rules={[{ label: 'Name the default', guidance: 'Use a verb-first primary label.', example: 'Publish' }, { label: 'Qualify alternatives', guidance: 'Explain how the related outcome differs.', example: 'Schedule publish' }, { label: 'Keep labels parallel', guidance: 'Use consistent action-object grammar.', example: 'Save as draft, Save as template' }, { label: 'Avoid generic trigger text', guidance: 'Use an accessible menu label tied to the action.', example: 'More publish actions' }]} /></ComponentDocSection>
<ComponentDocSection id="examples" title="Examples" description="Controlled menu visibility and loading support workflows that coordinate overlays and asynchronous action state."><div className="component-doc-stack"><ComponentPreview title="Controlled action family"><SplitPreview /></ComponentPreview><CodeBlock filename="ControlledPublish.tsx" code={CONTROLLED} /></div></ComponentDocSection>
<ComponentDocSection id="props-api" title="Props / API" description="SplitButton extends div attributes; each alternative defines identity, content, icon, availability, consequence, and execution."><PropsTable props={PROPS} /></ComponentDocSection>
<ComponentDocSection id="related-components" title="Related components" description="Choose based on action hierarchy and how many commands must remain visible."><RelatedComponents items={[{ name: 'Button', href: '/components/button', description: 'Run one clear action', icon: 'ti-square-rounded' }, { name: 'DropdownMenu', href: '/components/dropdown-menu', description: 'Expose equal-priority actions', icon: 'ti-menu-2' }, { name: 'Toolbar', href: '/components/toolbar', description: 'Keep several contextual actions visible', icon: 'ti-layout-navbar' }, { name: 'CommandBar', href: '/components/command-bar', description: 'Search a broad command set', icon: 'ti-command' }]} /></ComponentDocSection>
</ComponentDocumentation></div> }
