'use client'

import { useState } from 'react'
import { SavedView, SavedViews } from 'omverse-ui'
import { PageHeader } from '@/components/ui/PageHeader'
import { ComponentPreview } from '@/components/ui/ComponentPreview'
import { CodeBlock } from '@/components/ui/CodeBlock'
import { PropsTable } from '@/components/ui/PropsTable'
import { AccessibilityChecklist, Anatomy, BehaviorGrid, ComponentDocSection, ComponentDocumentation, ContentGuidelines, GuidanceList, KeyboardTable, RelatedComponents, StateMatrix } from '@/components/docs/ComponentDocumentation'
const PROPS=[{name:'views',type:'readonly SavedView[]',default:'required',description:'Governed saved-view collection.'},{name:'value',type:'string',default:'undefined',description:'Controlled active view identifier.'},{name:'defaultValue',type:'string',default:'undefined',description:'Initial active view.'},{name:'onValueChange',type:'(id: string) => void',default:'undefined',description:'Runs when a view becomes active.'},{name:'title',type:'ReactNode',default:"'Saved views'",description:'Visible collection heading.'},{name:'searchable',type:'boolean',default:'true',description:'Enables local name filtering.'},{name:'onCreate',type:'() => void',default:'undefined',description:'Shows and handles create view.'},{name:'onRename',type:'(view) => void',default:'undefined',description:'Handles rename.'},{name:'onDuplicate',type:'(view) => void',default:'undefined',description:'Handles duplication.'},{name:'onDelete',type:'(view) => void',default:'undefined',description:'Handles deletion.'},{name:'onSetDefault',type:'(view) => void',default:'undefined',description:'Handles default assignment.'},{name:'disabled',type:'boolean',default:'false',description:'Disables the collection.'},{name:'loading',type:'boolean',default:'false',description:'Shows view resolution progress.'},{name:'emptyState',type:'ReactNode',default:"'No saved views'",description:'No-result content.'},{name:'variant',type:"'outlined' | 'filled' | 'raised'",default:"'outlined'",description:'Controls surface treatment.'},{name:'size',type:"'sm' | 'md' | 'lg'",default:"'md'",description:'Controls row density.'}] as const
const BASIC=`import { SavedViews } from 'omverse-ui'

<SavedViews views={projectViews} value={activeView} onValueChange={setActiveView}
  onCreate={openCreateView} onRename={openRenameView} onDelete={confirmDelete} />`
const CONTROLLED=`<SavedViews views={views} value={route.viewId} onValueChange={(id) => navigate({ viewId: id })} variant="filled" />`
const VIEWS: SavedView[] = [
  { id: 'mine', name: 'My open work', detail: 'Assigned to me · Open', meta: 'You · Updated today', default: true },
  { id: 'risk', name: 'Projects at risk', detail: 'Health is at risk or blocked', meta: 'Maya · Updated yesterday', shared: true },
  { id: 'launch', name: 'Q4 launches', detail: 'Launch date this quarter', meta: 'Program office · Updated Aug 12', shared: true },
]

function SavedViewsPreview() {
  const [views, setViews] = useState<SavedView[]>(VIEWS)
  const [selected, setSelected] = useState('mine')

  return (
    <SavedViews
      views={views}
      value={selected}
      searchable
      onValueChange={(id) => setSelected(id)}
      onCreate={() => {
        const id = `view-${Date.now()}`
        setViews((current) => [...current, { id, name: `Custom view ${current.length + 1}`, detail: 'Created in this example', meta: 'You · Just now' }])
        setSelected(id)
      }}
      onRename={(view) => setViews((current) => current.map((item) => (item.id === view.id ? { ...item, name: `${item.name} (renamed)` } : item)))}
      onDuplicate={(view) => {
        setViews((current) => [...current, { ...view, id: `view-${Date.now()}`, name: `${view.name} (copy)` }])
      }}
      onDelete={(view) => {
        setViews((current) => current.filter((item) => item.id !== view.id))
        setSelected((previous) => (previous === view.id ? 'mine' : previous))
      }}
      onSetDefault={(view) => {
        setViews((current) => current.map((item) => (item.id === view.id ? { ...item, default: true } : { ...item, default: false })))
      }}
    />
  )
}
export default function SavedViewsPage(){return <div><PageHeader breadcrumb={['Components','Enterprise','SavedViews']} title="SavedViews" description="SavedViews selects and manages reusable query, filter, and layout configurations." tags={['Controlled selection','Search','Defaults','Sharing','Management actions']}/><ComponentDocumentation>
<ComponentDocSection id="overview" title="Overview" description="Use SavedViews when people repeatedly return to named combinations of filters, sorting, columns, and layout in data-heavy enterprise workflows."><div className="component-doc-stack"><ComponentPreview title="Project views" description="Choose a saved configuration, search the collection, or open its management actions."><SavedViewsPreview/></ComponentPreview><CodeBlock filename="ProjectViews.tsx" code={BASIC}/></div></ComponentDocSection>
<ComponentDocSection id="anatomy" title="Anatomy" description="SavedViews combines collection-level discovery and creation with identifiable, selectable, and manageable view rows."><Anatomy preview={<div className="component-anatomy-visual saved-views-anatomy"><header><span>Saved views<small>3 views</small></span><button>＋ New</button></header><label>⌕ Search views</label><section><i>♧</i><span><b>My open work</b><small>Assigned to me · Open</small></span><em>Default</em><button>⋮</button></section><span className="component-anatomy-marker component-anatomy-marker--leader-down" style={{top:-28,left:42}}>1</span><span className="component-anatomy-marker component-anatomy-marker--leader-down" style={{top:-28,right:32}}>2</span><span className="component-anatomy-marker component-anatomy-marker--leader-right" style={{top:66,left:-26}}>3</span><span className="component-anatomy-marker component-anatomy-marker--leader-up" style={{bottom:-28,left:55}}>4</span><span className="component-anatomy-marker component-anatomy-marker--leader-up" style={{bottom:-28,right:18}}>5</span></div>} items={[{number:1,name:'Collection header',description:'Names the saved-view set and states its count.'},{number:2,name:'Create action',description:'Starts a new saved configuration workflow.'},{number:3,name:'Search',description:'Filters saved views by name.'},{number:4,name:'View row',description:'Shows identity, scope, ownership, and recency.'},{number:5,name:'Management action',description:'Opens allowed operations for one view.'}]}/></ComponentDocSection>
<ComponentDocSection id="when-to-use" title="When to use" description="Use when configurations are valuable enough to name, revisit, share, or govern."><GuidanceList tone="do" items={[{title:'Reuse complex configurations',description:'Restore filters, sorting, columns, and layout together.'},{title:'Support personal and shared workflows',description:'Distinguish ownership and shared availability.'},{title:'Establish a default lens',description:'Let a team or person choose the view opened first.'}]}/></ComponentDocSection>
<ComponentDocSection id="when-not-to-use" title="When not to use" description="Prefer direct controls when configuration is temporary, trivial, or not persistable."><GuidanceList tone="dont" items={[{title:'Do not replace active filters',description:'Use FilterBar to show and edit current conditions.'},{title:'Do not save one simple choice',description:'Use Select or SegmentedControl.'},{title:'Do not imply persistence',description:'Avoid saved views when the product cannot reliably restore state.'}]}/></ComponentDocSection>
<ComponentDocSection id="variants" title="Variants" description="Surface treatment and density adapt SavedViews to side panels, embedded workspaces, and standalone management pages."><BehaviorGrid items={[{icon:'ti-border-all',title:'Outlined',description:'Default bounded collection.'},{icon:'ti-square-filled',title:'Filled',description:'Tonal collection inside a larger surface.'},{icon:'ti-shadow',title:'Raised',description:'Independent view switcher surface.'},{icon:'ti-arrows-minimize',title:'Density',description:'Small, medium, and large row spacing.'}]}/></ComponentDocSection>
<ComponentDocSection id="states" title="States" description="Selection communicates the active configuration; availability and management are represented separately."><StateMatrix rows={[{state:'Default',trigger:'No interaction',visual:'Available rows',interaction:'Choose a view'},{state:'Selected',trigger:'View activated',visual:'Primary row and bookmark',interaction:'Current configuration'},{state:'Search result',trigger:'Query entered',visual:'Matching names only',interaction:'Select or clear query'},{state:'Empty',trigger:'No views or matches',visual:'Empty-state content',interaction:'Create or revise search'},{state:'Loading',trigger:'Views resolving',visual:'Progress status',interaction:'Selection disabled'},{state:'Disabled',trigger:'View unavailable',visual:'Reduced emphasis',interaction:'Cannot select or manage'}]}/></ComponentDocSection>
<ComponentDocSection id="behavior" title="Behavior" description="SavedViews owns collection interaction while the application owns serialization, persistence, authorization, routing, and destructive confirmation."><BehaviorGrid items={[{icon:'ti-bookmark',title:'Activation',description:'Selecting a row requests restoration of its configuration.'},{icon:'ti-search',title:'Discovery',description:'Search filters names without changing the active view.'},{icon:'ti-dots-vertical',title:'Management',description:'Only supplied operations appear in each action menu.'},{icon:'ti-lock',title:'Governance',description:'Applications decide ownership and permitted mutations.'}]}/></ComponentDocSection>
<ComponentDocSection id="accessibility" title="Accessibility" description="Native controls, current-page semantics, explicit menu names, and status text make selection and management independently understandable."><div className="component-doc-stack"><KeyboardTable rows={[{keys:['Tab'],action:'Moves through search, creation, views, and management controls.'},{keys:['Enter','Space'],action:'Activates the focused view or action.'},{keys:['Esc'],action:'Closes an open management menu when implemented by the host.'}]}/><AccessibilityChecklist items={['Give the collection a visible heading.','Expose the active view with aria-current.','Name management buttons with the associated view.','Represent shared and default status in text, not icon alone.','Keep selection separate from row management actions.','Announce loading and empty results.']}/></div></ComponentDocSection>
<ComponentDocSection id="content-guidelines" title="Content guidelines" description="Names and metadata should help people recognize the restored configuration before activating it."><ContentGuidelines rules={[{label:'Name the outcome',guidance:'Describe the records people will see.',example:'Projects at risk'},{label:'Summarize conditions',guidance:'Use concise readable filter language.',example:'Health is at risk or blocked'},{label:'Identify scope',guidance:'State owner or shared availability.',example:'Program office · Shared'},{label:'Use direct actions',guidance:'Name management operations with verbs.',example:'Rename, Duplicate, Delete'}]}/></ComponentDocSection>
<ComponentDocSection id="examples" title="Examples" description="Controlled selection can synchronize a saved view with routing, deep links, and browser history."><div className="component-doc-stack"><ComponentPreview title="Shared operations views"><div className="saved-views-demo saved-views-demo--compact"><header><span><strong>Operations views</strong><small>2 shared views</small></span></header><div><article className="selected"><button aria-current="page"><i>♧</i><span><strong>Renewals this month</strong><small>Stage is renewal · Close date this month</small></span></button></article><article><button><i>♧</i><span><strong>Escalated accounts</strong><small>Priority is urgent</small></span></button></article></div></div></ComponentPreview><CodeBlock filename="RoutedViews.tsx" code={CONTROLLED}/></div></ComponentDocSection>
<ComponentDocSection id="props-api" title="Props / API" description="SavedViews extends section attributes; each SavedView defines identity, descriptive metadata, status, and availability."><PropsTable props={PROPS}/></ComponentDocSection>
<ComponentDocSection id="related-components" title="Related components" description="SavedViews restores configurations; related components create, edit, and apply their constituent parts."><RelatedComponents items={[{name:'FilterBar',href:'/components/filter-bar',description:'Edit active filter conditions',icon:'ti-filter'},{name:'DataTable',href:'/components/data-table',description:'Render configured records and columns',icon:'ti-table'},{name:'SearchField',href:'/components/search-field',description:'Run an ad hoc query',icon:'ti-search'},{name:'DropdownMenu',href:'/components/dropdown-menu',description:'Present view management operations',icon:'ti-menu-2'}]}/></ComponentDocSection>
</ComponentDocumentation></div>}
